import os


def var2bool(name):
    return os.getenv(name, 'False').lower() in ('true', '1', 't')


check_active_replication_slot = var2bool("CHECK_ACTIVE_REPLICATION_SLOT")
check_active_sessions = var2bool("CHECK_ACTIVE_SESSIONS")
check_autoanalyze_count_per_day = var2bool("CHECK_AUTOANALYZE_COUNT_PER_DAY")
check_autoanalyze_count_per_hour = var2bool("CHECK_AUTOANALYZE_COUNT_PER_HOUR")
check_autoanalyze_count_per_min = var2bool("CHECK_AUTOANALYZE_COUNT_PER_MIN")
check_autovacuum_count_per_day = var2bool("CHECK_AUTOVACUUM_COUNT_PER_DAY")
check_autovacuum_count_per_hour = var2bool("CHECK_AUTOVACUUM_COUNT_PER_HOUR")
check_autovacuum_count_per_min = var2bool("CHECK_AUTOVACUUM_COUNT_PER_MIN")
check_autovacuum_freeze_max_age = var2bool("CHECK_AUTOVACUUM_FREEZE_MAX_AGE")
check_autovacuum_multixact_freeze_max_age = var2bool("CHECK_AUTOVACUUM_MULTIXACT_FREEZE_MAX_AGE")
check_blocked_sessions = var2bool("CHECK_BLOCKED_SESSIONS")
check_checkpoints_requested = var2bool("CHECK_CHECKPOINTS_REQUESTED")
check_checkpoints_timed = var2bool("CHECK_CHECKPOINTS_TIMED")
check_connections_utilization = var2bool("CHECK_CONNECTIONS_UTILIZATION")
check_count_replication_slots = var2bool("CHECK_COUNT_REPLICATION_SLOTS")
check_deadlocks = var2bool("CHECK_DEADLOCKS")
check_idle_in_transaction_aborted_sessions = var2bool("CHECK_IDLE_IN_TRANSACTION_ABORTED_SESSIONS")
check_idle_in_transaction_sessions = var2bool("CHECK_IDLE_IN_TRANSACTION_SESSIONS")
check_idle_sessions = var2bool("CHECK_IDLE_SESSIONS")
check_inactive_replication_slot = var2bool("CHECK_INACTIVE_REPLICATION_SLOT")
check_invalid_indexes = var2bool("CHECK_INVALID_INDEXES")
check_lock_mode = var2bool("CHECK_LOCK_MODE")
check_lock_type = var2bool("CHECK_LOCK_TYPE")
check_max_connections = var2bool("CHECK_MAX_CONNECTIONS")
check_n_tables_eligible_for_autovacuum = var2bool("CHECK_N_TABLES_ELIGIBLE_FOR_AUTOVACUUM")
check_not_granted_lock = var2bool("CHECK_NOT_GRANTED_LOCK")
check_oldest_open_idl_in_transaction = var2bool("CHECK_OLDEST_OPEN_IDL_IN_TRANSACTION")
check_oldest_open_transaction = var2bool("CHECK_OLDEST_OPEN_TRANSACTION")
check_oldest_replication_slot_lag_gb_behind = var2bool("CHECK_OLDEST_REPLICATION_SLOT_LAG_GB_BEHIND")
check_oldest_replication_slot_lag_gb_behind_per_slot = var2bool("CHECK_OLDEST_REPLICATION_SLOT_LAG_GB_BEHIND_PER_SLOT")
check_oldest_xid = var2bool("CHECK_OLDEST_XID")
check_percent_towards_emergency_autovacuum = var2bool("CHECK_PERCENT_TOWARDS_EMERGENCY_AUTOVACUUM")
check_percent_towards_wraparound = var2bool("CHECK_PERCENT_TOWARDS_WRAPAROUND")
check_queries_canceled_due_to_lock_deadlocks = var2bool("CHECK_QUERIES_CANCELED_DUE_TO_LOCK_DEADLOCKS")
check_queries_canceled_due_to_lock_timeouts = var2bool("CHECK_QUERIES_CANCELED_DUE_TO_LOCK_TIMEOUTS")
check_result_table_stat_n_mod_since_analyze = var2bool("CHECK_RESULT_TABLE_STAT_N_MOD_SINCE_ANALYZE")
check_ride_entity_index_stat = var2bool("CHECK_RIDE_ENTITY_INDEX_STAT")
check_stat_tup_del_pct = var2bool("CHECK_STAT_TUP_DEL_PCT")
check_stat_tup_upd_pct = var2bool("CHECK_STAT_TUP_UPD_PCT")
check_table_stat_autoanalyze_count = var2bool("CHECK_TABLE_STAT_AUTOANALYZE_COUNT")
check_table_stat_autovacuum_count = var2bool("CHECK_TABLE_STAT_AUTOVACUUM_COUNT")
check_table_stat_dead_tup_percent = var2bool("CHECK_TABLE_STAT_DEAD_TUP_PERCENT")
check_table_stat_idx_tup_fetch = var2bool("CHECK_TABLE_STAT_IDX_TUP_FETCH")
check_table_stat_n_dead_tup = var2bool("CHECK_TABLE_STAT_N_DEAD_TUP")
check_table_stat_n_live_tup = var2bool("CHECK_TABLE_STAT_N_LIVE_TUP")
check_table_stat_n_tup_del = var2bool("CHECK_TABLE_STAT_N_TUP_DEL")
check_table_stat_n_tup_hot_upd = var2bool("CHECK_TABLE_STAT_N_TUP_HOT_UPD")
check_table_stat_n_tup_ins = var2bool("CHECK_TABLE_STAT_N_TUP_INS")
check_table_stat_n_tup_upd = var2bool("CHECK_TABLE_STAT_N_TUP_UPD")
check_table_stat_seq_tup_read = var2bool("CHECK_TABLE_STAT_SEQ_TUP_READ")
check_table_stat_total_fts_scan = var2bool("CHECK_TABLE_STAT_TOTAL_FTS_SCAN")
check_table_stat_total_idx_scan = var2bool("CHECK_TABLE_STAT_TOTAL_IDX_SCAN")
check_table_stat_tup_ins_pct = var2bool("CHECK_TABLE_STAT_TUP_INS_PCT")
check_total_connections = var2bool("CHECK_TOTAL_CONNECTIONS")
check_total_db_size_in_gb = var2bool("CHECK_TOTAL_DB_SIZE_IN_GB")
check_tup_deleted = var2bool("CHECK_TUP_DELETED")
check_tup_fetched = var2bool("CHECK_TUP_FETCHED")
check_tup_inserted = var2bool("CHECK_TUP_INSERTED")
check_tup_returned = var2bool("CHECK_TUP_RETURNED")
check_tup_updated = var2bool("CHECK_TUP_UPDATED")
check_wait_event = var2bool("CHECK_WAIT_EVENT")
check_xact_commit = var2bool("CHECK_XACT_COMMIT")
check_xact_commit_ratio = var2bool("CHECK_XACT_COMMIT_RATIO")
check_xact_rollback = var2bool("CHECK_XACT_ROLLBACK")
